### ISSUE TITLE
Fix Header Style

### ISSUE THREAD

**Issue by inlife** [johnthepink/dark-slack#1]
yo

Thnx for the beautiful dark style!
Im not sure why there so small amount of stars yet 😉 

Anyway, there is a small problem:
![image](https://cloud.githubusercontent.com/assets/2182108/23175327/b5fa39d2-f867-11e6-9647-908192a414ed.png)
(everything else is properly dark)

Seems like they've changed some stuff. 
Will it be possible for you to fix update it some future update?

Thank you!

**Comment by johnthepink** [comment]
@Inlife thanks for the report! I will try to look in to it soon. Should be a simple CSS fix.

**Comment by caiceA** [comment]
``
![screen shot 2017-09-30 at 01 29 39 2](https://user-images.githubusercontent.com/16766231/31039568-f7d5b524-a57e-11e7-8876-c4d50c679f13.png)

**Comment by caiceA** [comment]
![screen shot 2017-09-30 at 01 29 34 2](https://user-images.githubusercontent.com/16766231/31039573-ffe6f7aa-a57e-11e7-8208-2ef85cc7cf4f.png)

**Comment by caiceA** [comment]
i am seeing this issue please can you fix this ?

**Comment by johnthepink** [comment]
@Inlife @caiceA see if #4 helped fix these issues for you?
